### ISSUE TITLE
Deploy OpenATO Demo

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [OpenATO/Roadmap#1]
### Overview

The goal of this epic is to deploy a demo version of the OpenATO user interface at demo.openato.com. This demo will allow users to sign up, log in, review the component library, work on multiple projects, add or remove components, and export control narratives.

### Problem

The assets from CivicActions/atoasap_api and CivicActions/atoasap_ui need to be moved into the OpenATO Github organization. The world needs to see what OpenATO is working on, and a public user interface is essential for this.

### Solution | Goal

To deploy the demo version of the OpenATO user interface at demo.openato.com, which will allow users to sign up, log in, review the component library, work on multiple projects, add or remove components, and export control narratives.

### References

- [CivicActions/atoasap_api](https://github.com/CivicActions/atoasap_api)
- [CivicActions/atoasap_ui](https://github.com/CivicActions/atoasap_ui)

### Acceptance Criteria

- [x] Assets from CivicActions/atoasap_api and CivicActions/atoasap_ui are successfully moved into the OpenATO Github organization
- [ ] A demo version of the OpenATO user interface is deployed at demo.openato.com
- [ ] Users are able to sign up and log in
- [ ] Users can review the component library
- [ ] Users can work on multiple projects
- [ ] Users can add or remove components
- [ ] Users can export control narratives

### Team

🖼️ Front End, 🍄 Back End, ⚙️ DevOps, ♿ Accessability, 🏰 Security
